### ISSUE TITLE
bug: Could not get lock /var/lib/dpkg/lock-frontend - open   AWS顽疾

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-template#16]
临时方案：
1. sudo lsof /var/lib/dpkg/lock-frontend 找到PID
2. sudo kill -9 1548
3. sudo rm /var/lib/dpkg/lock-frontend
4. sudo dpkg --configure -a

https://www.ostechnix.com/how-to-fix-e-could-not-get-lock-var-lib-dpkg-lock-error-on-ubuntu/

**Comment by qiaofeng1227** [comment]
Done
